[package]
name = "Symbol"
version = { workspace = true }
authors = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]

[dev_dependencies]
JestGlobals = { workspace = true }
