[tools]
rotrieve = { source = "roblox/rotriever", version = "0.5.1" }
rojo = { source = "rojo-rbx/rojo", version = "7.0.0" }
selene = { source = "Kampfkarren/selene", version = "0.18.2" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.13.1" }
