[tools]
rotrieve = { source = "roblox/rotriever", version = "0.5.5" }
rojo = { source = "rojo-rbx/rojo", version = "7.2.0" }
selene = { source = "Kampfkarren/selene", version = "0.21.1" }
stylua = { source = "JohnnyMorganz/StyLua", version = "=0.14.3" }
