[tools]
rotrieve = { source = "roblox/rotriever", version = "0.4.2" }
rojo = { source = "rojo-rbx/rojo", version = "6.2.0" }
selene = { source = "Kampfkarren/selene", version = "0.13" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.10" }
