[package]
name = "LuauPolyfill"
version = "0.2.3"
author = "Paul Doyle <pdoyle@roblox.com>"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@2.0.1"
TestEZ = "github.com/roblox/jest-roblox@2.0.1"
RegExp = "github.com/roblox/luau-regexp@0.1.2"
Promise = "github.com/evaera/roblox-lua-promise@3.1.0"
