[workspace]
version = "1.2.2"
members = ["modules/*"]
default_member = "LuauPolyfill"
authors = [
    "Chris Trześniewski <k.trzesniewski@gmail.com>",
    "Kyle Mitofsky <kylemit@gmail.com>",
    "Matt Hargett <plaztiksyke@gmail.com>",
    "Olivier Trepanier <otrepanier@roblox.com>",
    "Paul Doyle <pdoyle@roblox.com>",
    "Raymond Ng <rng@roblox.com>",
    "Zack Ovits <zack@boatbomber.com>",
]

[workspace.dependencies]
JestGlobals = "github.com/roblox/jest-roblox@2.4.1"
TestEZ = "github.com/roblox/jest-roblox@2.4.1"
RegExp = "github.com/roblox/luau-regexp@0.1.3"
Promise = "github.com/evaera/roblox-lua-promise@3.1.0"

# Patch latest copies of collections into jest dependencies to dodge lint
[config.patch."github.com/roblox/luau-polyfill"]
Collections = { path = "modules/collections" }
