[package]
name = "LuauPolyfill"
version = "0.2.1"
author = "Paul Doyle <pdoyle@roblox.com>"
content_root = "src"

[dev_dependencies]
JestRoblox = "github.com/roblox/jest-roblox@2.0.0-pre.1"
RegExp = "github.com/roblox/luau-regexp@0.1.0"
Promise = "github.com/evaera/roblox-lua-promise@3.1.0"
