return function()
	local join = require(script.Parent.Parent.join)

	describe("Join", function()
		local arr = { "Wind", "Water", "Fire" }
		it("should join strings arrays without specified separator", function()
			expect(join(arr)).to.equal("Wind,Water,Fire")
		end)
		it("should join strings arrays with specified separator", function()
			expect(join(arr, ", ")).to.equal("Wind, Water, Fire")
			expect(join(arr, " + ")).to.equal("Wind + Water + Fire")
			expect(join(arr, "")).to.equal("WindWaterFire")
		end)
		it("should join empty array", function()
			expect(join({})).to.equal("")
			expect(join({}, ", ")).to.equal("")
			expect(join({}, " + ")).to.equal("")
			expect(join({}, "")).to.equal("")
		end)
		it("should not add separator for array with single element", function()
			expect(join({"foo"}, ", ")).to.equal("foo")
			expect(join({"foo"}, " + ")).to.equal("foo")
			expect(join({"foo"}, "")).to.equal("foo")
		end)
	end)
end
