[package]
name = "Boolean"
version = { workspace = true }
authors = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
Number = { path = "../number" }

[dev_dependencies]
JestGlobals = { workspace = true }
