[package]
name = "roblox/luau-polyfill-string"
description = "String utilities, part of luau-polyfill"
version = "1.2.5"

license = "MIT"

authors = ["Roblox <no-reply@roblox.com>"]

realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

repository = "https://github.com/Roblox/luau-polyfill"
exclude = ["rotriever.toml"]

[dependencies]
Number = "roblox/luau-polyfill-number@=1.2.5"
ES7Types = "roblox/luau-polyfill-es7-types@=1.2.5"
