return {
	every = require(script.every),
	filter = require(script.filter),
	find = require(script.find),
	findIndex = require(script.findIndex),
	from = require(script.from),
	indexOf = require(script.indexOf),
	isArray = require(script.isArray),
	map = require(script.map),
	reduce = require(script.reduce),
	shift = require(script.shift),
	slice = require(script.slice),
	some = require(script.some),
	splice = require(script.splice),
}
