[package]
name = "Console"
version = { workspace = true }
authors = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
Collections = { path = "../collections" }

[dev_dependencies]
JestGlobals = { workspace = true }
